name: Test Reusable

on:
  workflow_call:
    inputs:
      greeting:
        type: string
        default: 'hello'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
