name: Test Reusable macOS

on:
  workflow_call:
    inputs:
      greeting:
        type: string
        default: 'hello'
        required: false
    secrets:
      TEST_SECRET:
        required: false

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ inputs.greeting }}
    steps:
      - run: echo "hello"
