name: Test Reusable macOS

on:
  workflow_call:
    inputs:
      greeting:
        type: string
        default: 'hello'
        required: false
    secrets:
      TEST_SECRET:
        required: false

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
